spring:
  application:
    name: Patron
  cloud:
    stream:
      bindings:
        requestHandler-in-0:
          destination: airplanes
      function:
        definition: requestHandler
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
---
spring:
  config:
    activate:
      on-profile: comm_nats
nats:
  spring:
    server: dockerhost:4222
