spring:
  application:
    name: Patron
  cloud:
    stream:
      bindings:
        requestHandler-in-0:
          destination: airplanes
      function:
        definition: requestHandler
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
---
spring:
  config:
    activate:
      on-profile: comm_nats
nats:
  spring:
    server: localhost:4222
---
spring:
  config:
    activate:
      on-profile: comm_redis
  redis:
    host: localhost
    port: 6379
---
spring:
  config:
    activate:
      on-profile: comm_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
---
spring:
  config:
    activate:
      on-profile: comm_activemq
  activemq:
    broker-url: tcp://localhost:61616
---
spring:
  config:
    activate:
      on-profile: comm_nsq
nsq:
  nsqlookupd-host: localhost
