spring:
  application:
    name: Patron
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
---
spring:
  config:
    activate:
      on-profile: different-profile
server:
  port: 9003
