image: openjdk:15-alpine

services:
  - docker:19-dind

variables:
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_CERTDIR: "/certs"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # all stages on separate containers anyway

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - echo `pwd`
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew --build-cache classes'

Test:
  stage: test
  before_script:
    - apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - './gradlew test'

Check:
  stage: check
  script:
    - './gradlew --build-cache check'
