image: openjdk:15-alpine

services:
  - docker:17-dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375" # needed in 17-dind
#  DOCKER_DRIVER: "overlay2"
#  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew classes'

Test:
  stage: test
  script:
    - './gradlew test'

Check:
  stage: check
  script:
    - './gradlew check'
