image: openjdk:15-alpine

services:
  - docker:17-dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375" # needed in 17-dind
#  DOCKER_DRIVER: "overlay2"
#  DOCKER_TLS_CERTDIR: "/certs"
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # todo Slower but more correct?

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - echo `pwd`
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew --build-cache classes' # todo Does this allow results to be re-used?

Test:
  stage: test
  before_script:
    - apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - './gradlew --build-cache test' # todo Does this allow results to be re-used?

Check:
  stage: check
  script:
    - './gradlew check'
