image: openjdk:15-alpine

services:
  - docker:17-dind

variables:
  # Tell Docker where to create certificates
  DOCKER_TLS_CERTDIR: "/certs"
  # Instruct Testcontainers where docker host and tls cert path is
  DOCKER_HOST: "tcp://docker:2375"
  #  DOCKER_TLS_VERIFY: 1
  #  DOCKER_CERT_PATH: "/certs"
  # all stages on separate containers anyway
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Needed for installing docker-compose
  CRYPTOGRAPHY_DONT_BUILD_RUST: 1

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - echo `pwd`
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew --build-cache classes'

Test:
  stage: test
  before_script:
    - apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose=1.27.4
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - './gradlew test'

Check:
  stage: check
  script:
    - './gradlew --build-cache check'
