#image: openjdk:15.0.1-slim

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03-dind

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  image: openjdk:15.0.1-slim
  script:
    - './gradlew classes'

Test:
  stage: test
  image: openjdk:15.0.1-slim
  script:
    - './gradlew test'

Check:
  stage: check
  image: openjdk:15.0.1-slim
  script:
    - './gradlew check'
