image: openjdk:15-alpine

services:
  - docker:17-dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375" # needed in 17-dind
#  DOCKER_DRIVER: "overlay2"
#  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - check

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew classes'

Test:
  stage: test
  before_script:
    - apk add --no-cache curl
    - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - './gradlew test'

Check:
  stage: check
  script:
    - './gradlew check'
