version: "3.6"
services:
  activemq:
    build: provision/activemq
    ports:
      - "61616:61616"
      - "8161:8161" # management, admin:admin
    environment:
      ACTIVEMQ_OPTS: "-Djetty.host=0.0.0.0"
