version: "3.6"
services:
  quote-system.prometheus:
    image: prom/prometheus:v2.17.1
    ports:
      - "9090:9090"
    volumes:
      - /benchmark-mq/provision/prometheus/etc/prometheus:/etc/prometheus

  quote-system.grafana:
    image: grafana/grafana:7.1.5
    ports:
      - "3000:3000"
    volumes:
      - volume-grafana-quote-system:/var/lib/grafana
      - /benchmark-mq/provision/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
