spring:
  application:
    name: Manufacturer
  cloud:
    stream:
      bindings:
        airplanesHandler-out-0:
          destination: airplanes
      source: airplanesHandler
server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: comm_nats
nats:
  spring:
    server: dockerhost:4222
