spring:
  application:
    name: Manufacturer
  cloud:
    stream:
      bindings:
        airplanesHandler-out-0:
          destination: airplanes
      source: airplanesHandler
server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: comm_nats
nats:
  spring:
    server: localhost:4222
---
spring:
  config:
    activate:
      on-profile: comm_redis
  redis:
    host: localhost
    port: 6379
---
spring:
  config:
    activate:
      on-profile: comm_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
---
spring:
  config:
    activate:
      on-profile: comm_activemq
  activemq:
    broker-url: tcp://localhost:61616
