name: Benchmark-mq CI

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: openjdk:15.0.1-slim

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Compile
        run: ./gradlew classes
